/**
 * U10 / KTD-9 — runtime round-trip verification.
 *
 * Every decoder is proof-carrying, so a *statement* cannot decode wrongly without
 * falling back to `raw()`. Verification exists for everything outside a
 * statement: a def key elided because the encoder looked like it would reproduce
 * it, a kind-level default read the wrong way, an object dropped entirely. Those
 * are invisible until the whole tree is loaded and exported again.
 *
 * The comparison is per object on purpose. "The bundles differ" tells a user
 * nothing they can act on; "`function signup` re-exports differently" points at
 * the file to open.
 */
import { describe, it, expect } from "vitest";
import { verifyBundles, reportMismatches } from "../../src/codegen/verify.js";
import { DecodeReport } from "../../src/codegen/report.js";

/** A bundle with one function and one table, by name. */
function bundle(functions: Array<Record<string, unknown>>, extra: Record<string, unknown> = {}) {
  return { payload: { partial: false, workspace: { name: "ws" }, function: functions, ...extra } };
}

describe("verifyBundles", () => {
  it("passes when the regenerated bundle matches object for object", () => {
    const a = bundle([{ name: "signup", description: "" }]);
    const b = bundle([{ name: "signup", description: "" }]);
    expect(verifyBundles(a, b)).toEqual({ ok: true, mismatches: [], omissions: [] });
  });

  it("names the object whose re-export differs, not the whole payload", () => {
    const result = verifyBundles(
      bundle([{ name: "signup", description: "hi" }, { name: "login" }]),
      bundle([{ name: "signup", description: "" }, { name: "login" }]),
    );
    expect(result.ok).toBe(false);
    expect(result.mismatches).toHaveLength(1);
    expect(result.mismatches[0]).toMatchObject({ payloadKey: "function", name: "signup" });
  });

  it("catches an object the generated tree dropped entirely", () => {
    // The failure mode a payload-wide deep-equal would also catch, but without
    // saying which object went missing — this is the common real-world case (an
    // object the ref index could not identify is skipped by assembly).
    const result = verifyBundles(bundle([{ name: "signup" }]), bundle([]));
    expect(result.mismatches[0]).toMatchObject({
      payloadKey: "function",
      name: "signup",
      detail: "missing from the generated tree",
    });
  });

  it("catches an object the generated tree invented", () => {
    const result = verifyBundles(bundle([]), bundle([{ name: "ghost" }]));
    expect(result.mismatches[0]!.detail).toContain("not in the source bundle");
  });

  it("names the differing key of a non-array section, not just the section", () => {
    // "workspace:(section) does not match" was true and useless — a workspace
    // object carries ~35 keys and the old message named none of them.
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", canonical: "a" } } },
      { payload: { workspace: { name: "ws", canonical: "b" } } },
    );
    expect(result.mismatches).toHaveLength(1);
    expect(result.mismatches[0]).toMatchObject({ payloadKey: "workspace", name: "canonical" });
  });

  it("compares a scalar section whole, since it has no keys to report against", () => {
    const result = verifyBundles({ payload: { partial: false } }, { payload: { partial: true } });
    expect(result.mismatches[0]).toMatchObject({ payloadKey: "partial", name: "(section)" });
  });

  it("reports a deliberately-dropped workspace secret as an omission, not a mismatch", () => {
    // The whole point of the split: declining to write an instance's crypto
    // material into a committed source tree is correct behavior, so it must not
    // read as a failed round trip.
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", secret: "s3cr3t", crypto: { iv: "x" } } } },
      { payload: { workspace: { name: "ws" } } },
    );
    expect(result.ok).toBe(true);
    expect(result.mismatches).toEqual([]);
    expect(result.omissions.map((o) => o.name).sort()).toEqual(["crypto", "secret"]);
    expect(result.omissions.every((o) => o.reason === "secret")).toBe(true);
  });

  it("reports a server-assigned workspace key as an omission", () => {
    // domain_prefix is generated by the instance and builds its hostnames —
    // redeploying it to another tenant would claim that tenant's routing.
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", domain_prefix: "813eef" } } },
      { payload: { workspace: { name: "ws" } } },
    );
    expect(result.ok).toBe(true);
    expect(result.omissions[0]).toMatchObject({ name: "domain_prefix", reason: "server-managed" });
  });

  it("treats the deliberately-emptied workspace.env as an omission, verified at top level", () => {
    // A real bundle carries env vars in BOTH workspace.env and top-level
    // payload.env. The encoder hoists to top-level (where the import reads them)
    // and blanks workspace.env rather than duplicating secrets — so every real
    // workspace with env vars would otherwise fail verification.
    const vars = [{ name: "A", value: "1", market_item: [] }];
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", env: vars }, env: vars } },
      { payload: { workspace: { name: "ws", env: [] }, env: vars } },
    );
    expect(result.ok).toBe(true);
    expect(result.omissions[0]).toMatchObject({ name: "env", reason: "relocated" });
  });

  it("still fails when the relocated env vars are actually lost", () => {
    // The `emptied` exemption covers only workspace.env. Dropping the top-level
    // copy too is real loss and must stay a hard failure.
    const vars = [{ name: "A", value: "1", market_item: [] }];
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", env: vars }, env: vars } },
      { payload: { workspace: { name: "ws", env: [] }, env: [] } },
    );
    expect(result.ok).toBe(false);
    expect(result.mismatches[0]).toMatchObject({ payloadKey: "env", name: "A" });
  });

  it("does not excuse an emptied key that is emitted with a DIFFERENT value", () => {
    // `emptied` means blank-or-absent, not "anything goes".
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", env: [{ name: "A", value: "1" }] } } },
      { payload: { workspace: { name: "ws", env: [{ name: "B", value: "2" }] } } },
    );
    expect(result.ok).toBe(false);
    expect(result.mismatches[0]).toMatchObject({ name: "env" });
  });

  it("does not excuse a listed key that is emitted with a DIFFERENT value", () => {
    // Only an absence can be a deliberate omission. Writing the wrong secret is
    // a real divergence no policy covers.
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", secret: "real" } } },
      { payload: { workspace: { name: "ws", secret: "wrong" } } },
    );
    expect(result.ok).toBe(false);
    expect(result.mismatches[0]).toMatchObject({ payloadKey: "workspace", name: "secret" });
    expect(result.omissions).toEqual([]);
  });

  it("does not excuse an unlisted workspace key that went missing", () => {
    // A key that is neither modeled nor on the policy list is a genuine gap and
    // has to stay a hard failure, or the list silently becomes a catch-all.
    const result = verifyBundles(
      { payload: { workspace: { name: "ws", something_new: 1 } } },
      { payload: { workspace: { name: "ws" } } },
    );
    expect(result.ok).toBe(false);
    expect(result.mismatches[0]).toMatchObject({ name: "something_new" });
  });

  it("reports objects in an unmodeled section as omissions, so a real pull verifies clean", () => {
    // payload.knowledge is a first-class engine object type this SDK decided not
    // to author in TypeScript. Its absence is policy, not loss.
    const result = verifyBundles(
      { payload: { knowledge: [{ name: "how-to" }], function: [] } },
      { payload: { knowledge: [], function: [] } },
    );
    expect(result.ok).toBe(true);
    expect(result.omissions[0]).toMatchObject({
      payloadKey: "knowledge",
      name: "how-to",
      reason: "unmodeled",
    });
  });

  it("compares under normalize(), so an engine-canonicalized difference is not a mismatch", () => {
    // Verification must not cry wolf on the same shapes the conformance corpus
    // already normalizes away, or `--no-verify` becomes the default habit.
    const result = verifyBundles(
      bundle([{ name: "signup", settings_registry: [] }]),
      bundle([{ name: "signup", settings_registry: null }]),
    );
    expect(result.ok).toBe(true);
  });
});

describe("reportMismatches", () => {
  it("folds mismatches into the report so every sink shows them", () => {
    // The README, the CLI summary, and the structured entries all read one
    // computed report — verification has to write there, not print separately.
    const report = new DecodeReport();
    reportMismatches(report, verifyBundles(bundle([{ name: "signup" }]), bundle([])));
    const group = report.summarize().byCategory.find((g) => g.category === "verify-mismatch");
    expect(group?.count).toBe(1);
    expect(report.renderMarkdown()).toContain("function:signup");
    expect(report.renderCli()).toContain("function:signup");
  });

  it("leaves a clean result alone", () => {
    const report = new DecodeReport();
    reportMismatches(report, verifyBundles(bundle([]), bundle([])));
    expect(report.entries).toEqual([]);
  });

  it("files omissions under their own category so they never read as mismatches", () => {
    const report = new DecodeReport();
    reportMismatches(
      report,
      verifyBundles(
        { payload: { workspace: { name: "ws", secret: "s" } } },
        { payload: { workspace: { name: "ws" } } },
      ),
    );
    const byCategory = report.summarize().byCategory;
    expect(byCategory.find((g) => g.category === "verify-mismatch")).toBeUndefined();
    expect(byCategory.find((g) => g.category === "expected-omission")?.count).toBe(1);
    expect(report.renderCli()).toContain("workspace:secret");
  });
});
