/**
 * Implied-input catalog per trigger `obj_type` (U1). Xano trigger inputs are
 * **fixed by type** — they are generated by `mvp:trigger_update_defaults` and
 * cannot be edited in the UI. This module is the SideStep mirror of that
 * generator: `impliedInputs(objType)` returns the exact input array Xano stores
 * for a trigger of that type.
 *
 * Source of truth (mirror, do not "fix"): the Xano engine's trigger
 * default-input generator (database / toolset / workspace / realtime, plus the
 * error-trigger input schema).
 *
 * Fields are built through the canonical `input.*` / `f.*` constructors + shared
 * `encodeInput`, so they carry the same stored shape and defaults as every other
 * SideStep input (`customize:{}`, `_xsid:""`, numeric `market_item`) and cannot
 * drift from the field encoder. The shipped `test/fixtures/triggers/*.json` carry
 * the older `customize:""` parser-generation format; conformance compares
 * structurally, normalizing that legacy drift and the engine-assigned `_xsid`.
 */
import type { InputXdo } from "../types/xdo.js";
import { input, encodeInput } from "../inputs/input.js";
import type { InputDescriptor } from "../inputs/input.js";
import { f } from "../fields/catalog.js";

/**
 * The stored trigger `obj_type`s. `agent`/`mcpServer` both map to `toolset`.
 *
 * `workspace_realtime_channel` is the LEGACY realtime channel trigger and stays
 * as-is; `realtime_server` and `channel` are the current realtime lifecycle
 * types (server connect/disconnect, channel join/leave). They are distinct
 * obj_types, not a replacement — v1 and v2 coexist.
 */
export type TriggerInputObjType =
  | "database"
  | "toolset"
  | "workspace"
  | "workspace_realtime_channel"
  | "realtime_server"
  | "channel"
  | "error";

/**
 * The `event` enum description on error triggers, carried verbatim from
 * `buildErrorTriggerInputSchema` so the AI-facing schema explains snapshot dedup
 * / regression / fixed semantics.
 */
const ERROR_EVENT_DESCRIPTION =
  'Which event fired the trigger. "new" fires on first capture and on every ' +
  "snapshot re-capture for non-ignored signatures (rate-limited by the ~5min " +
  'snapshot dedup window). "regression" fires when a previously-fixed signature ' +
  "re-occurs (the fix didn't hold, or the same bug regressed back). \"fixed\" " +
  "fires when a user marks a signature as fixed.";

/**
 * The connecting-client input shared by both realtime lifecycle trigger types
 * (`realtime_server` connect/disconnect and `channel` join/leave). `permissions`
 * is what gates the client's realtime row/table access.
 */
function realtimeClientInput(): InputDescriptor {
  return input.object(
    {
      extras: f.json(),
      permissions: f.object({ dbo_id: f.int(), row_id: f.text() }, { required: true }),
    },
    { required: true },
  );
}

/** Named descriptor map → encoded input array (in declared order). */
function encodeAll(map: Record<string, InputDescriptor>): InputXdo[] {
  return Object.entries(map).map(([name, d]) => encodeInput(name, d));
}

/** Per-`obj_type` descriptor maps. Insertion order is the stored input order. */
const CATALOG: Record<TriggerInputObjType, () => Record<string, InputDescriptor>> = {
  // Database trigger — new/old rows, action op, datasource label.
  database: () => ({
    new: input.json(),
    old: input.json(),
    action: input.enum(["insert", "update", "delete", "truncate"], { required: true }),
    // NOTE (Xano quirk, mirror don't fix): `updateDefaults` stores `datasource`
    // as `text` but copy-pastes the `action` enum into its `values`. We mirror
    // the stored shape exactly rather than "correcting" it.
    datasource: input.text({ required: true, values: ["insert", "update", "delete", "truncate"] }),
  }),

  // Toolset trigger (MCP server / agent) — the connected toolset + its tools.
  toolset: () => ({
    toolset: input.object(
      {
        id: f.int({ description: "The toolset ID" }),
        name: f.text({ description: "The toolset name", methods: ["trim"] }),
        instructions: f.text({ description: "The toolset instructions", methods: ["trim"] }),
      },
      { description: "The toolset being connected to" },
    ),
    tools: input.list(
      input.object({
        id: f.int({ description: "The tool ID" }),
        name: f.text({ description: "The tool name", methods: ["trim"] }),
        instructions: f.text({ description: "The tool instructions", methods: ["trim"] }),
      }),
      { description: "The list of tools on the MCP Server" },
    ),
  }),

  // Workspace lifecycle trigger — branch action + the branches involved.
  workspace: () => ({
    to_branch: input.object({ id: f.int(), label: f.text({ methods: ["trim"] }) }),
    from_branch: input.object({ id: f.int(), label: f.text({ methods: ["trim"] }) }),
    action: input.enum(["branch_live", "branch_merge", "branch_new"], { required: true }),
  }),

  // Realtime channel trigger — message/join action + channel/client/options/payload.
  workspace_realtime_channel: () => ({
    action: input.enum(["message", "join"], { required: true, default: "message" }),
    channel: input.text({ required: true }),
    client: input.object(
      {
        extras: f.json(),
        permissions: f.object(
          { dbo_id: f.int(), row_id: f.text() },
          { required: true },
        ),
      },
      { required: true },
    ),
    options: input.object({ authenticated: f.bool(), channel: f.text() }),
    payload: input.json({ required: true, nullable: true }),
  }),

  // Realtime SERVER lifecycle trigger — connect/disconnect on a realtime server.
  // Mirrors the engine's stored input array exactly: the action enum carries NO
  // default (unlike the legacy channel trigger's `"message"`), and `client` is
  // the same connecting-client object both realtime lifecycle types use.
  realtime_server: () => ({
    action: input.enum(["connect", "disconnect"], { required: true }),
    realtime_server: input.text({ required: true }),
    client: realtimeClientInput(),
  }),

  // Realtime CHANNEL lifecycle trigger — join/leave/deliver on a channel. Same
  // shape as the server type with the addressed channel path in place of the
  // server name.
  //
  // The action enum carries all THREE actions the engine declares for this type,
  // regardless of which ones a given trigger enables: the enum describes what
  // `action` can hold at runtime, and the per-trigger selection lives in `meta`.
  //
  // VERIFIED AGAINST A LIVE CAPTURE: a `deliver`-only trigger stores exactly this
  // input array — the same three entries as a join/leave one, and the same enum
  // values in the same order. That was the open question worth not guessing,
  // because `deliver` runs per recipient and its stack rewrites the payload, so a
  // `payload` entry and a recipient identity were the natural things to expect.
  //
  // They are NOT declared, and that is the engine's shape rather than a gap here: a
  // deliver stack receives the payload and the recipient at RUNTIME under reserved
  // keys that never enter the stored input array. SideStep mirrors the stored array,
  // so they are correspondingly absent from the typed `t` handle.
  channel: () => ({
    action: input.enum(["join", "leave", "deliver"], { required: true }),
    channel: input.text({ required: true }),
    client: realtimeClientInput(),
  }),

  // Error trigger — the error signature schema (verbatim from buildErrorTriggerInputSchema).
  error: () => ({
    event: input.enum(["new", "regression", "fixed"], { description: ERROR_EVENT_DESCRIPTION }),
    id: input.int({
      description: "The error signature row id. Use to build deep links into the error-logs UI.",
    }),
    signature: input.text({ description: "Stable hash that identifies this error signature." }),
    error: input.object(
      {
        code: f.text({ description: "Machine-readable error code." }),
        message: f.text({ description: "Human-readable error message." }),
      },
      { description: "Error code and message captured from the failing run." },
    ),
    caller: input.object(
      {
        type: f.text({
          description: "Caller kind (api, function, task, middleware, trigger, unknown).",
        }),
        id: f.int({ description: "Caller object id." }),
        name: f.text({ description: "Caller object name.", nullable: true }),
      },
      { description: "Where the error originated. Null on 'fixed' events.", nullable: true },
    ),
    statement: input.object(
      {
        name: f.text({ description: "Statement name." }),
        xsid: f.text({ description: "Statement xsid within the function stack." }),
      },
      { description: "Failing statement. Null on 'fixed' events.", nullable: true },
    ),
    actor: input.object(
      {
        id: f.int({ description: "User id." }),
        name: f.text({ description: "User name.", nullable: true }),
      },
      {
        description: "User who marked the error as fixed. Populated only for 'fixed' events.",
        nullable: true,
      },
    ),
    count: input.object(
      {
        total: f.int({ description: "Total occurrences since first seen." }),
        last_hour: f.int({ description: "Occurrences in the last hour." }),
      },
      { description: "Occurrence counts for this signature." },
    ),
    first_seen: input.text({ description: "ISO-8601 UTC timestamp of the first occurrence." }),
    last_seen: input.text({ description: "ISO-8601 UTC timestamp of the most recent occurrence." }),
    fixed_at: input.text({
      description: "ISO-8601 UTC timestamp the error was marked fixed. Null otherwise.",
      nullable: true,
    }),
  }),
};

/**
 * The implied input array for a trigger `obj_type`, matching what Xano's
 * `updateDefaults` stores. `agent`/`mcpServer` triggers pass `"toolset"`.
 */
export function impliedInputs(objType: TriggerInputObjType): InputXdo[] {
  return encodeAll(CATALOG[objType]());
}
