/**
 * Generate `examples/implementations/_auto.ts` — the barrel that imports every
 * statement / value / filter / field example and buckets each exported def by
 * kind (a table has `schema`, a query has `verb`, everything else is a function).
 *
 * The hand-authored `index.ts` consumes those buckets and hand-wires the small,
 * stable set of object-kind examples (`kinds/`). Run: `npm run examples:index`.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../examples/implementations", import.meta.url));
const AUTO_DIRS = ["statements", "values", "filters", "fields"];

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith("_")) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith(".ts")) out.push(full);
  }
  return out;
}

const files: string[] = [];
for (const d of AUTO_DIRS) {
  try {
    files.push(...walk(join(ROOT, d)));
  } catch {
    // dir may not exist yet
  }
}
files.sort();

const imports = files
  .map((f, i) => {
    const rel = "./" + relative(ROOT, f).replace(/\.ts$/, ".js");
    return `import * as m${i} from "${rel}";`;
  })
  .join("\n");

const list = files.map((_, i) => `m${i}`).join(", ");

const body = `/**
 * AUTO-GENERATED by scripts/gen-examples-index.ts — DO NOT EDIT BY HAND.
 *
 * Every statement / value / filter / field example, bucketed by kind. Regenerate
 * with \`npm run examples:index\` after adding or removing an example file.
 *
 * ${files.length} example modules collected.
 */
${imports}

type Def = Record<string, unknown>;
const MODULES: Record<string, unknown>[] = [${list}];

const autoTables: Def[] = [];
const autoQueries: Def[] = [];
const autoFunctions: Def[] = [];

for (const mod of MODULES) {
  for (const value of Object.values(mod)) {
    if (!value || typeof value !== "object") continue;
    const v = value as Def;
    if ("schema" in v) autoTables.push(v);
    else if ("verb" in v) autoQueries.push(v);
    else autoFunctions.push(v);
  }
}

export { autoTables, autoQueries, autoFunctions };
`;

writeFileSync(join(ROOT, "_auto.ts"), body);
console.log(`Wrote examples/implementations/_auto.ts (${files.length} modules).`);
