/**
 * Route-manifest emission (`sidestep routes <entry> --emit <path>`).
 *
 * "Derive paths from the defs, never hardcode them" is the SDK's central
 * frontend rule, and following it costs the whole core runtime: importing one
 * query def for its `getPath()` pulls the statement factories in with it,
 * because the `s.*`/`c.*` CALLS that build the def run at module load and cannot
 * be tree-shaken. Measured on a minimal Vite app, that is ~37 kB of minified JS
 * for a single path string — 48x the hand-written equivalent (issue #223).
 *
 * The documented escape hatch is a hand-typed `ROUTES` table, which is the exact
 * thing the rule exists to prevent: the strings rot silently when a def's `name`
 * changes, and the compile-time key checking is lost.
 *
 * This module removes the trade-off. Everything a frontend needs — the verb, the
 * resolved `/api:<canonical>/<name>` path, and the `{param}` names — is already
 * known at export time. Writing it out as plain data yields the same typed,
 * rename-safe contract at near-zero bundle cost.
 *
 * The emitted file imports NOTHING. It is generated TypeScript with an inline
 * interpolator, so the guarantee is structural rather than a tree-shaking hope:
 * there is no `@sidestep/core` specifier in it for a bundler to follow.
 *
 * Keyed by each query's real `name` — the same string the def carries — so no
 * identifier is invented from it, and a backend rename surfaces as a compile
 * error at every call site rather than a 404 at runtime.
 */
import { parsePathParams } from "../kinds/path-params.js";
import type { HttpVerb } from "../kinds/query.js";

/** One endpoint, as the emitter needs it. */
export interface RouteEntry {
  /** The query's `name`, `{param}` markers intact — the manifest's key. */
  name: string;
  verb: HttpVerb;
  /** The api group's resolved canonical URL token. */
  canonical: string;
}

/** Emit-time failure: a route the manifest cannot describe. */
export class RouteManifestError extends Error {}

/** A TypeScript string literal for `value`, safe in single quotes. */
function literal(value: string): string {
  return JSON.stringify(value);
}

/**
 * The generated module's source text.
 *
 * `routes` are expected pre-resolved (canonical already looked up) and are
 * sorted here so the output is deterministic — the file is committed and diffed,
 * and a re-run that reorders it would show as spurious churn.
 */
export function renderRouteManifest(routes: readonly RouteEntry[]): string {
  const sorted = [...routes].sort(
    (a, b) => a.canonical.localeCompare(b.canonical) || a.name.localeCompare(b.name),
  );

  const seen = new Set<string>();
  const rows = sorted.map((route) => {
    if (seen.has(route.name)) {
      throw new RouteManifestError(
        `Two endpoints are both named "${route.name}". The route manifest keys on the endpoint ` +
          `name, so the names must be unique across api groups. Rename one.`,
      );
    }
    seen.add(route.name);
    const params = parsePathParams(`route "${route.name}"`, route.name);
    const path = `/api:${route.canonical}/${route.name.replace(/^\/+/, "")}`;
    return { ...route, params, path };
  });

  const entries = rows
    .map((r) => `  ${literal(r.name)}: { verb: ${literal(r.verb)}, path: ${literal(r.path)} },`)
    .join("\n");

  // One overload per parameterized route, so the params argument is typed
  // exactly — a missing key, a wrong key, or params on a static route are all
  // compile errors rather than runtime throws at request time.
  const overloads = rows
    .map((r) =>
      r.params.length === 0
        ? `export function routePath(name: ${literal(r.name)}): string;`
        : `export function routePath(name: ${literal(r.name)}, params: { ${r.params
            .map((p) => `${literal(p)}: string | number`)
            .join("; ")} }): string;`,
    )
    .join("\n");

  return `${HEADER}
export const ROUTES = {
${entries}
} as const;

/** Every endpoint name in this workspace. */
export type RouteName = keyof typeof ROUTES;

${overloads}
${IMPLEMENTATION}`;
}

const HEADER = `/**
 * GENERATED by \`sidestep routes --emit\`. Do not edit.
 *
 * Plain data plus one interpolator — this file imports nothing, so a frontend
 * gets the typed path/verb contract without pulling the SDK runtime into its
 * bundle. Regenerate after changing an endpoint's name, verb, or api group.
 */
`;

/**
 * The emitted interpolator.
 *
 * Mirrors \`fillPathParams\` rule for rule — unknown key, missing or empty value,
 * non-finite number, and a value containing \`/\` all throw. Inlined rather than
 * imported because importing it is the bundle cost this file exists to avoid;
 * the round-trip test pins the two implementations to the same behaviour.
 */
const IMPLEMENTATION = `
export function routePath(name: RouteName, params?: Record<string, string | number>): string {
  const route = ROUTES[name];
  if (!route) throw new Error(\`routePath: unknown route "\${String(name)}".\`);
  const declared = [...route.path.matchAll(/\\{([^/{}]+)\\}/g)].map((m) => m[1]!);
  for (const key of Object.keys(params ?? {})) {
    if (!declared.includes(key)) {
      throw new Error(
        \`routePath("\${String(name)}"): \\\`\${key}\\\` is not a {param} of this route.\` +
          (declared.length ? \` Expected: \${declared.join(", ")}.\` : " This route is static."),
      );
    }
  }
  return route.path.replace(/\\{([^/{}]+)\\}/g, (_all, key: string) => {
    const value = (params ?? {})[key];
    if (value === undefined || value === null || value === "") {
      throw new Error(\`routePath("\${String(name)}"): missing a value for the path param \\\`\${key}\\\`.\`);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new Error(\`routePath("\${String(name)}"): the path param \\\`\${key}\\\` is \${value}.\`);
    }
    const text = String(value);
    if (text.includes("/")) {
      throw new Error(
        \`routePath("\${String(name)}"): the path param \\\`\${key}\\\` cannot contain "/" — \` +
          "it would address a different route.",
      );
    }
    return text;
  });
}
`;
